nimble: Ignore nimble compile warnings
Will cause compilation warning if NDEBUG is defined We can't modify the code of the external library, so let's ignore it

services/ans/src/ble_svc_ans.c:450:9: error: variable 'rc' set but not used [-Werror=unused-but-set-variable]
  450 |     int rc;
      |         ^~

Signed-off-by: yinshengkai <yinshengkai@xiaomi.com>