examples/nrf24l01_term/nrf24l01_term.c: Appease nxstyle
Still has a few errors because of include/nuttx/wireless/nrf24l01.h.

examples/nrf24l01_term/nrf24l01_term.c:125:33: error: Mixed case identifier found
examples/nrf24l01_term/nrf24l01_term.c:129:15: error: Mixed case identifier found