fix builtin_list.c:58:10: fatal error: builtin_proto.h: No such file or directory
Make builtin_list.c instead of builtin_list.o depend on builtin_proto.h and builtin_proto.c

Change-Id: I1ac6c9b7172d433f5d74c9dd248869adf1f5e387
Signed-off-by: Xiang Xiao <xiaoxiang@xiaomi.com>