TESTING_NAND_SIM: Add depends on
apps/testing/nand_sim/nand_sim_main.c:172:(.text.nand_main+0x93): undefined reference to `nand_ram_initialize'
collect2: error: ld returned 1 exit status

Signed-off-by: zhangshoukui <zhangshoukui@xiaomi.com>