nimble: Update version to cd8ab38c3da91b71dd428979153a408f38d3b02e
which contain the following fix:
commit cd8ab38c3da91b71dd428979153a408f38d3b02e
Author: Xiang Xiao <xiaoxiang@xiaomi.com>
Date:   Thu May 20 15:43:50 2021 +0800

nuttx: fix error: use of undeclared identifier 'ENOMEM'

Signed-off-by: Xiang Xiao <xiaoxiang@xiaomi.com>
Change-Id: Idd832450d98306750ece8307ec7eef5c0c367a48